name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Устанавливаем Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Проверка кода
        run: go vet ./...

      - name: Запуск тестов
        run: go test ./... -v